### ISSUE TITLE
tkinter not installed

### ISSUE THREAD

**Issue by zarozombie** [grantjenks/free-python-games#20]
Let me know if this is just me....

I have Python 3.6.7 and tkinter was not install initially (I'm using ubuntu)

had to run 
sudo apt-get install python3-tk

to get tinkter working

below was my first attempt of running after

works fine now.
-------------------------------------------

user@computer:~/programming/python/free-python-games$ python3 -m freegames.snake
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lcc/programming/python/free-python-games/freegames/snake.py", line 12, in <module>
    from turtle import *
  File "/usr/lib/python3.6/turtle.py", line 107, in <module>
    import tkinter as TK
ModuleNotFoundError: No module named 'tkinter'

**Comment by grantjenks** [comment]
It's not just you. It's a feature of Ubuntu and other linux distros. The "apt-get install python3" command is minimal and doesn't include tkinter 🤷

**Comment by Tsering-Wongdi-Sherpa** [comment]
Thank you it really work
